ignoredBuiltDependencies:
  - '@nestjs/core@11.1.18(@nestjs/common@11.1.18(reflect-metadata@0.2.2)(rxjs@7.8.2))(@nestjs/platform-express@11.1.18)(reflect-metadata@0.2.2)(rxjs@7.8.2)'
  - unrs-resolver@1.11.1

onlyBuiltDependencies:
  - '@nestjs/core'
  - unrs-resolver
